In [1]:
import numpy

In [2]:
n=numpy.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [3]:
type(n)

numpy.ndarray

In [4]:
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [5]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [21]:
n=numpy.asarray([[123,12,123,12,33],[],[]])

/tmp/ipykernel_9855/2936976748.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  n=numpy.asarray([[123,12,123,12,33],[],[]])


In [16]:
type(n)

numpy.ndarray

In [30]:
nu=numpy.arange(15)
nu

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [36]:
num=nu.reshape(3,5)

In [38]:
num[0:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [39]:
num[0:2,2:4]

array([[2, 3],
       [7, 8]])

In [40]:
num[:,2:4]

array([[ 2,  3],
       [ 7,  8],
       [12, 13]])

In [41]:
num[1,2]

7

In [43]:
for i in num:
    print(i)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]


In [44]:
for i in num.T:
    print(i)

[ 0  5 10]
[ 1  6 11]
[ 2  7 12]
[ 3  8 13]
[ 4  9 14]


In [45]:
for i in num.flat:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


In [46]:
num

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [47]:
# Stacking and Splitting

In [50]:
numstack=numpy.hstack((num,num))
numstack

array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 10, 11, 12, 13, 14]])

In [55]:
numstack=numpy.hstack((num,num,num))
numstack

array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9,  5,  6,  7,  8,  9,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 10, 11, 12, 13, 14, 10, 11, 12, 13, 14]])

In [53]:
numst=numpy.hsplit(numstack,3)

In [54]:
numst

[array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])]

In [62]:
numst=numpy.hsplit(numstack,5)
numst

[array([[ 0,  1,  2],
        [ 5,  6,  7],
        [10, 11, 12]]),
 array([[ 3,  4,  0],
        [ 8,  9,  5],
        [13, 14, 10]]),
 array([[ 1,  2,  3],
        [ 6,  7,  8],
        [11, 12, 13]]),
 array([[ 4,  0,  1],
        [ 9,  5,  6],
        [14, 10, 11]]),
 array([[ 2,  3,  4],
        [ 7,  8,  9],
        [12, 13, 14]])]

In [65]:
numst=numpy.vsplit(numstack,3)
numst

[array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]]),
 array([[5, 6, 7, 8, 9, 5, 6, 7, 8, 9, 5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14, 10, 11, 12, 13, 14, 10, 11, 12, 13, 14]])]